file='.env'
echo "FB_API_KEY=$FB_API_KEY" > $file
echo "FB_AUTH_DOMAIN=$FB_AUTH_DOMAIN" >> $file
echo "FB_DATABASE_URL=$FB_DATABASE_URL" >> $file
echo "FB_PROJECT_ID=$FB_PROJECT_ID" >> $file
echo "FB_STORAGE_BUCKET=$FB_STORAGE_BUCKET" >> $file
echo "FB_MESSAGE_SENDER_ID=$FB_MESSAGE_SENDER_ID" >> $file
echo "FB_APP_ID=$FB_APP_ID" >> $file
echo "FB_MEASUREMENT_ID=$FB_MEASUREMENT_ID" >> $file
echo "OWM_KEY=$OWM_KEY" >> $file
echo "API_URL=$API_URL" >> $file
echo "STRIPE_KEY=$STRIPE_KEY" >> $file
echo "STRIPE_REDIRECT=$STRIPE_REDIRECT" >> $file
echo "STRIPE_PREMIUM_PRICE_ID=$STRIPE_PREMIUM_PRICE_ID" >> $file
