# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: NPM Install
      run: npm install --force
    - name: NPM Build
      run: npm run build

  release:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: NPM Install
        run: npm install --force
      - name: Create Release
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: sh scripts/create_env_file.sh
        env:
            FB_API_KEY: ${{ secrets.FB_API_KEY }}
            FB_AUTH_DOMAIN: ${{ secrets.FB_AUTH_DOMAIN }}
            FB_DATABASE_URL: ${{ secrets.FB_DATABASE_URL }}
            FB_PROJECT_ID: ${{ secrets.FB_PROJECT_ID }}
            FB_STORAGE_BUCKET: ${{ secrets.FB_STORAGE_BUCKET }}
            FB_MESSAGE_SENDER_ID: ${{ secrets.FB_MESSAGE_SENDER_ID }}
            FB_APP_ID: ${{ secrets.FB_APP_ID }}
            FB_MEASUREMENT_ID: ${{ secrets.FB_MEASUREMENT_ID }}
            OWM_KEY: ${{ secrets.OWM_KEY }}
            API_URL: ${{ secrets.API_URL }}
      - run: npm run build
      - id: version
        run: |
          version=$(npm pkg get version | tr -d '"')
          echo "package_version=${version}" >> $GITHUB_OUTPUT
    outputs:
      package_version: ${{ steps.version.outputs.package_version }}

  deploy:
    needs: release
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Update package.json
        id: version
        run: |
          sed -i "s/0.0.0-semver/${{needs.release.outputs.package_version}}/g" package.json
      - run: npm install --force
      - run: npm run deploy:ci
